# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’

target 'GNews' do
pod 'AFNetworkActivityLogger', '~> 2.0'
pod 'AFNetworking', '2.2.1'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'MediaRSSParser', '~> 1.0'
end

target 'GNewsTests' do

end

target 'GNewsUITests' do

end

